"""create warehouses and zone tables

Revision ID: 8c762212de67
Revises: add_user_login_fields
Create Date: 2026-07-11 11:04:17.631180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c762212de67'
down_revision: Union[str, Sequence[str], None] = 'add_user_login_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('request_note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_requests_warehouse_id'), 'layout_requests', ['warehouse_id'], unique=False)
    op.create_table('zone_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_sections_warehouse_id'), 'zone_sections', ['warehouse_id'], unique=False)
    op.create_table('layout_request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('proposed_data', sa.JSON(), nullable=True),
    sa.Column('previous_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['layout_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_request_items_request_id'), 'layout_request_items', ['request_id'], unique=False)
    op.create_table('zone_stock_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['zone_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_stock_entries_section_id'), 'zone_stock_entries', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_stock_entries_section_id'), table_name='zone_stock_entries')
    op.drop_table('zone_stock_entries')
    op.drop_index(op.f('ix_layout_request_items_request_id'), table_name='layout_request_items')
    op.drop_table('layout_request_items')
    op.drop_index(op.f('ix_zone_sections_warehouse_id'), table_name='zone_sections')
    op.drop_table('zone_sections')
    op.drop_index(op.f('ix_layout_requests_warehouse_id'), table_name='layout_requests')
    op.drop_table('layout_requests')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
